const { Strain } = require('../models');

const strainData = [
  {
    strain_name: 'Blue Dream',
    description: "A potent cross between the ever popular classic strains Blueberry and Haze, a slightly sativa-dominant strain shrouded in mystery. With a relatively high THC level range that averages at a low of 17% and a high of 24%, this dreamy bud has more than just good looks and flavor to bring to the table. The delicious flavors of blueberry and sugar are long lasting and stay in the air and on your tongue long after the smoke has gone. However, because it is super potent it does have extremely beneficial elements for patients who suffer from chronic fatigue, depression, and lack of appetite.",
    thc_level:"18%",
    strain_type_id: 3,
    effect_id: 1,
    usage_id: 1,
    aroma_id: 1,
    review_id: null,
    img: "https://s3-us-west-2.amazonaws.com/leafly-images/flower-images/blue-dream.png?w=1200&fm=jpg",
},
{
    strain_name: 'Acapulco Gold',
    description: "Acapulco Gold is a Sativa dominant hybrid known for the golden hue of its green and/or brownish buds. This old strain is said to produce a powerful cerebral high that raises one's mood without producing overpowering feelings of happiness. Instead, the cerebral high mixes with a calming body high for a relaxing experience. Sufferers of disorders such as General Anxiety Disorder or PTSD use this strain to find relief from stress and anxiety. Those dealing with depression use it to lift their mood. The body high can also relieve chronic aches and pains.",
    thc_level:"23%",
    strain_type_id: 2,
    effect_id: 2,
    usage_id: 1,
    aroma_id: 1,
    review_id: null,
    img: "https://images.leafly.com/flower-images/acapulco.jpg",
  },
  {
    strain_name: 'Gelato',
    description: "Gelato is a hybrid crossed from taste-engineered parents Thin Mint Girl Scout Cookies and fruity indica Sunset Sherbert. With a balanced, mellow high and a universally appealing flavor profile, this is a great strain for social use. This is a strain with immediate visual appeal: bright orange pistils stand out against forest green leaves that are accented by shades of deep purple. The purple hues come about when high concentrations of pigments called anthocyanins are stimulated by cold weather in the vegetative stage. The carefree elevation of mood can also offer temporary relief from the troubling symptoms associated with anxiety, depression, and PTSD.",
    thc_level:"25%",
    strain_type_id: 3,
    effect_id: 3,
    usage_id: 2,
    aroma_id: 3,
    review_id: null,
    img: "https://s3-us-west-2.amazonaws.com/leafly-images/flower-images/gelato.jpg?w=1200&fm=jpg",
  },
  {
    strain_name: 'Wedding Cake',
    description: "Wedding Cake is a sweet strain, of course, but it packs a spicy aftermath (just like marriage). It is great for calming down and going out, even for doing nothing the ideal people watcher strain. Wedding Cake leans towards Indica (60/40) and like GSC has leaves that are both dark and light green, with dense buds, and numerous sugary crystals.The strain works wonders for users who want to control their nerves or anxiety. Neuromuscular regulation is also a term that gets tossed around, meaning that Wedding Cake can help people deal with depression and reduce symptoms related to muscular sclerosis and fibromyalgia.",
    thc_level:"25%",
    strain_type_id: 3,
    effect_id: 1,
    usage_id: 3,
    aroma_id: 1,
    review_id: null,
    img: "https://leafly-public.s3-us-west-2.amazonaws.com/strains/photos/m2y50HYRBu0dHY4JSdSx_wedding-cake_jman.jpg?w=1200&fm=jpg",
  },
  {
    strain_name: 'Bubba Kush',
    description: "The original L.A. breeder claims that while one parent was an OG Kush plant, the other was an unnamed Northern Lights phenotype brought back from Mardi Gras in New Orleans; this unnamed mother strain affectionately came to be known as “Bubba,” and has since been lost. Sweet hashish flavors with subtle notes of chocolate and coffee come through on the exhale, delighting the palate as powerful relaxation takes over. From head to toe, muscles ease with heaviness as dreamy euphoria blankets the mind, crushing stress while bringing happy moods. Unusually for such an indica-heavy strain, the high begins with a warped, disoriented sensation in the head. In large enough doses, it can serve as treatment for insomnia as well. Many users describe increased appetite as a common side effect_name. Well-suited to nighttime or lazy daytime use.",
    thc_level:"23%",
    strain_type_id: 3,
    effect_id: 5,
    usage_id: 1,
    aroma_id: 2,
    review_id: null,
    img: "https://images.hytiva.com/Bubba-Kush.jpg?mw667-mh1000",
  },
  {
    strain_name: 'Purple Kush',
    description: "Known as Purple Hindu Kush, Purple Kush is a pure indica that sets itself apart from other indica hybrids with its eye-catching colors and pleasant taste. Purple Kush is a cross between two South-Central Asian indica landraces: Hindu Kush, from the mountainous Pakistan-Afghanistan border, and a purple-tinged variety of Afghani. With 100% indica genetics, it provides a slow and relaxing full body stone. Named a Top 10 Kush Strain by High Times magazine in 2016, Purple Kush has THC level composition ranging from 17% to as much as 27%. the buds also have a standout taste. The initial impression is similar to the odor of Afghani strains, with an earthy, almost sandalwood musk. Closer inspection brings out sweet and fruity notes of grape.",
    thc_level:"27%",
    strain_type_id: 1,
    effect_id: 1,
    usage_id: 4,
    aroma_id: 2,
    review_id: null,
    img: "https://leafly-public.s3-us-west-2.amazonaws.com/strains/photos/YA0VM3EQdWeg3RdGTbXG_purple-kush_jman.jpg?w=1200&fm=jpg",
  },
  {
    strain_name: 'Original Glue (GG4)',
    description: "This plant has won more awards than we can even list. a strain that will absolutely knock you on your ass, aromas of diesel, pine, and chocolate will permeate the air, so make sure you smoke this one in private. Not only is she potent when it comes to psychoactive effects, but the palate this bud brings will either make you fall in love or never try it again. Mental effects are certainly strong with a euphoria that just will not quit, but mostly this strain is known for her ability to glue you to the couch with ease. If nothing else, perhaps you will enjoy a friendly conversation with your bag of chips and laugh a bit harder at your favorite shows, because you certainly will not be accomplishing much of anything else.",
    thc_level:"30%",
    strain_type_id: 1,
    effect_id: 5,
    usage_id: 1,
    aroma_id: 2,
    review_id: 3,
    img: "https://images.weedmaps.com/photos/products/000/032/343/original/50611_remedy_gorilla-glue-_4_1.jpg?fit=fill&fill=solid&fill-color=ffffff&h=640&w=640&auto=format",
  },
  {
    strain_name: 'Sour Diesel',
    description: "Sour Diesel, also known as  is a popular sativa marijuana strain made by crossing Chemdawg and Super Skunk. Sour Diesel effects are dreamy, cerebral, fast-acting and energizing. This strain features a pungent flavor profile that smells like diesel. Medical marijuana patients choose Sour Diesel to help relieve symptoms associated with depression, pain, and stress. The effects begin as a surge of cerebral energy, which promotes creativity and a feeling of get-up-and-go. The stimulation and brain-electrifying feelings would get anyone up and moving (the 26% THC level high does not hurt either). It can help you fight fatigue, get your appetite moving again, combat that pesky migraine, or even help with mood disorders.",
    thc_level:"26%",
    strain_type_id: 2,
    effect_id: 1,
    usage_id: 5,
    aroma_id: 4,
    review_id: 1,
    img: "https://leafly-public.s3-us-west-2.amazonaws.com/strains/photos/5SPDG4T4TcSO8PgLgWHO_SourDiesel_AdobeStock_171888473.jpg?w=1200&fm=jpg",
  },
  {
    strain_name: 'Champagne Kush',
    description: "Champagne Kush, also just called Champagne, is a 50/50 hybrid with bright to medium toned green buds that are covered in orange hairs and smell faintly of the beverage after which they are named. Despite the name of Kush, this strain's Indica effects are fewer, providing a light body high that may make users feel very tingly. The strain's cerebral effects are much more prominent, filling users' mind with a warming, mood elevating euphoria. Users of this strain report a rise in the desire to socialize, becoming much more talkative. A good strain for use during the daytime, Champagne Kush's  tingling body high may ease some lesser chronic aches and pains. However, it is more often chosen by those looking to fight the chaining effects of stress, anxiety and depression related disorders. A few find that this strain helps them sleep easier as well.",
    thc_level:"15%",
    strain_type_id: 1,
    effect_id: 1,
    usage_id: 1,
    aroma_id: 5,
    review_id: null,
    img: "https://images.leafly.com/flower-images/pink-champagne-fixed.jpg",
  },
  {
    strain_name: 'Raspberry Tart',
    description: "Many individuals find that Raspberry Tart is just what they need to tackle a busy day, Crossing Amina Berry, Brian Berry, and Amnesia Haze brings the flavorful Raspberry Tart to life. With raspberry, vanilla, pine, and fuel flavors, Raspberry Tart has an uplifting high that is geared toward daytime smokers looking to focus.",
    thc_level:"21%",
    strain_type_id: 2,
    effect_id: 1,
    usage_id: 5,
    aroma_id: 6,
    review_id: 3,
    img: "https://images.hytiva.com/Raspberry-Picker-1.jpg?mw667-mh1000",
  },
];

const seedStrain = () => Strain.bulkCreate(strainData);

module.exports = seedStrain;